### ISSUE TITLE
Do you consider adding IPOPT in benchmarks?

### ISSUE THREAD

**Issue by Capri2014** [oxfordcontrol/osqp_benchmarks#1]
Great work! It would be great if IPOPT can be added into benchmarks as well.

**Comment by bstellato** [comment]
I think it should not be a problem to add IPOPT. However, I see some issues:

- Ipopt might not perform as well as the other solvers since it is not tailored to QPs but for more general problems.
- **Timing is an issue.** There is no clear way to get the cpu time taken by Ipopt in the python interfaces I know of ([cyipopt](https://github.com/matthias-k/cyipopt) or [pyipopt](https://github.com/xuy/pyipopt)). To include the functions and gradients evaluation (not only the cpu time), I could time directly how long it takes in Python to call the `solve` function. However, this might also be unfair since it includes the Python interpreter lag. Do you know any way to get the Ipopt cpu time from the python interface?

See also this https://github.com/matthias-k/cyipopt/issues/17

**Comment by Capri2014** [comment]
@bstellato Thanks for the reply. Yes, counting cpu time in python for the whole calculation for Ipopt is difficult...
